docsumo data added
Know-Nepal/tech-companies pull request #48
Opened 2023-03-24 09:11 UTC by ankurgajurel

## What kind of change does this PR introduce? 

- [ ] Bug Fix
- [ ] Documentation change
- [ -] Added new company
- [ ] Other(s)

## Why was this change needed?

 
Docsumo data added

## Other information

2023-03-24 15:18 UTC, thenishantsapkota requested changes

2023-03-24 15:18 UTC, thenishantsapkota commented on data/docsumo.json
> +    "phone": null,
Can you provide a phone number for the place?

2023-03-25 05:34 UTC, thenishantsapkota commented
If the number isn't Nepali, then unfortunately we cannot accept this PR at this time.
Please do make another PR if you find a Nepali Number for the company. 
Thank you for understanding!

2023-03-25 05:34 UTC, closed without merging

2023-03-25 12:40 UTC, ankurgajurel commented
> If the number isn't Nepali, then unfortunately we cannot accept this PR at this time. Please do make another PR if you find a Nepali Number for the company. Thank you for understanding!

sure dai looking forward to contributing ajhai