added alpas
Know-Nepal/tech-companies pull request #66
Opened 2023-10-05 05:17 UTC by shresritik

## What kind of change does this PR introduce? 

- [ ] Bug Fix
- [ ] Documentation change
- [x] Added new company
- [ ] Other(s)

## Why was this change needed?
added alpas technology data
 

## Other information

2023-10-05 18:33 UTC, TheLearneer requested changes
Please make the fixes 🙏

2023-10-06 00:49 UTC, shresritik commented on data/companies.json
> +      "website": "https://www.yarsa.io/",
Ok, I have corrected the company name. Please check it now

2023-10-06 15:39 UTC, TheLearneer approved these changes
LGMT

2023-10-07 01:39 UTC, shresritik commented
Please merge and close the PR

2023-10-07 04:15 UTC, merged